### ISSUE TITLE
unable to install manually or through xcode (incompatible with vscode 1.27.1)

### ISSUE THREAD

**Issue by petemyron** [LoyieKing/Smalise#1]
Code doesn't really give any useful error message as to why it is incompatible, but it fails to install. When trying to install this plugin through the store, it says:
![image](https://user-images.githubusercontent.com/627937/69100793-cd672700-0a12-11ea-8d44-a51fef8227b8.png)

When trying to install this plugin manually, it says:
![image](https://user-images.githubusercontent.com/627937/69100811-db1cac80-0a12-11ea-94b2-76407fb556d7.png)

**Comment by LoyieKing** [comment]
what's your vscode's version？maybe it's too low

**Comment by petemyron** [comment]
Why closed? Sorry, I figured you'd see the version of VS Code in the original post (1.27.1). I shoulda replied earlier!

I don't think my Code version is very far out of date.

**Comment by LoyieKing** [comment]
> Why closed? Sorry, I figured you'd see the version of VS Code in the original post (1.27.1). I shoulda replied earlier!
> 
> I don't think my Code version is very far out of date.

the version need to be bigger than 1.33.0,you may need to update you vscode
