### ISSUE TITLE
onHover for valid Resource IDs

### ISSUE THREAD

**Issue by surendrajat** [LoyieKing/Smalise#14]
For a resource ID in hexadecimal format like this:
```smali
const v1, 0x7f050001
```
when hover on `0x7f050001` an `onHover` tip could be shown, after searching in `R$*.smali` files, like this:
```
R$layout.main
```
or simply:
```
layout:main
```

**Advantage**: It will save the time of doing search and find the id each time these values are encountered.

**Comment by LoyieKing** [comment]
https://github.com/LoyieKing/Smalise/pull/24
