### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by surendrajat** [LoyieKing/Smalise#19]
Hi. I've been uploading Smalise to open-vsx.org for people who don't use official VS Code builds, but it has been removed due to missing license. Could you please add a proper LICENSE file and update `package.json`?

**Comment by LoyieKing** [comment]
added~

**Comment by surendrajat** [comment]
@LoyieKing thanks. Could you bump patch version too? :)

EDIT: I've anyway published it here: https://open-vsx.org/extension/LoyieKing/smalise
