### ISSUE TITLE
Syntax Highlighting breaks when a class name is prefixed with a minus

### ISSUE THREAD

**Issue by FoseFx** [LoyieKing/Smalise#20]
In a project of mine I came across these two lines of smali code:
```smali
    new-instance v1, Lpkg/-$$Lambda$MainActivity$wqafgufGsPnnOcBuIzzHVhnovxo;
    invoke-direct {v1, p0}, Lpkg/-$$Lambda$MainActivity$wqafgufGsPnnOcBuIzzHVhnovxo;-><init>(Lpkg/MainActivity;)V
```

Which were highlighted like this:

![Bildschirmfoto von 2021-04-09 15-41-12](https://user-images.githubusercontent.com/22842759/114189049-0d051a80-994a-11eb-8005-2d27c152d9f3.png)

I assume this is because of the "-" prefix as without them syntax highlighting works:

![Bildschirmfoto von 2021-04-09 15-42-45](https://user-images.githubusercontent.com/22842759/114189243-48074e00-994a-11eb-8ad2-c229f1dc5eb0.png)

**Comment by LoyieKing** [comment]
fixed~
https://github.com/LoyieKing/Smalise/commit/14cabdd11bc70b8c841908f928d55335b23c7cd8
