### ISSUE TITLE
Lazy String parse

### ISSUE THREAD

**Issue by maksz42** [LoyieKing/Smalise#6]
The regex.String /(".*?")/ in parser.js shouldn't be lazy as it won't catch escaped double quotes \\".

**Comment by Gh0u1L5** [comment]
Thanks for the feedback @maksz42 . The lazy string matching is necessary for handling codes like the following
```
new-instance v8, Ljava/util/HashMap;
invoke-direct {v8}, Ljava/util/HashMap;-><init>()V
.local v8, "eventMap":Ljava/util/Map;, "Ljava/util/Map<Landroid/arch/lifecycle/ClassesInfoCache$MethodReference;Landroid/arch/lifecycle/Lifecycle$Event;>;":
```

Notice that there are multiple strings in a single line, thus a non-lazy regexp will match the part
`
"eventMap":Ljava/util/Map;, "Ljava/util/Map<Ljava/lang/String;Landroid/arch/lifecycle/Lifecycle$Event;>;"
`

Now, to fix the issue you reported, I'd suggest to use this regexp: 
```regexp
".*?(?<!\\)"
```

It matches an ending `"` without any leading `\`, which should handle the escaped double quotes perfectly.

I think I'll make a new PR to add some new features this weekend, and I'd like to fix this bug in the upcoming PR.

**Comment by maksz42** [comment]
Honestly, I'm bad at regex for now but what you think about that?
`".*?(?<!\\)(?:\\\\)*"`
It should catch escaped '\\' too.

**Comment by Gh0u1L5** [comment]
Ah ha, an interesting edge case. After careful thinking, I think the correct way to handle it is:
```regexp
"(?:[^"\\]|\\.)*"
```

`[^"\\]` matches any character that's not `"` nor `\\`, and `\\.` matches any escaped character.
