### ISSUE TITLE
Support radix conversion

### ISSUE THREAD

**Issue by surendrajat** [LoyieKing/Smalise#8]
First of all thanks for this nice extension. I'm ~planning to write~ [writing](https://github.com/Surendrajat/APKLab) an extension to automate apk reversing workflow with apktool, apksigner, jadx, etc. also because I found this extension for vs code :)

About the issue, res IDs in android are in decimal when decompiled to Java with tools like jadx. Each time I want to follow a res ID, I have to do `printf '%d' 0x23` thing in a terminal or open calculator. JEB decompiler has this cool feature where you click on a HEX value and press B so you can cycle through DEC-OCT-HEX radix values which makes it super easy to work with the IDs and other values such as time periods.
Although that's not a smali feature what do you think about implementing it in this extension? Say a shortcut to toggle between HEX and DEC values or right-click and convert radix.

**Comment by LoyieKing** [comment]
https://github.com/LoyieKing/Smalise/pull/24
